@if(session('Thankyou'))
    @include('modals._thankyou')
@endif
@if(session('Message'))
    @include('modals._message')
@endif
@if(session('MessageFailed'))
    @include('modals._message-failed')
@endif